version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=minhacasa
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234


