version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=minhacasa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  
  spring-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    depends_on:
      - postgres-db
  
  angular-app:
    build:
      context: ./frontend/minhacasa
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - spring-app





