package com.gabriel.minhacasa.config;

import com.gabriel.minhacasa.domain.Immobile;
import com.gabriel.minhacasa.domain.User;
import com.gabriel.minhacasa.domain.enums.*;
import com.gabriel.minhacasa.repository.ImmobileRepository;
import com.gabriel.minhacasa.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

@Component
@RequiredArgsConstructor
@Profile("prod")
@Slf4j
public class Prod_FirstDataConfig implements ApplicationRunner {
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final ImmobileRepository immobileRepository;

    @Override
    public void run(ApplicationArguments args) throws Exception {
        User admin = User.builder()
                .id(1L)
                .name("admin")
                .phone("00000000000")
                .whatsapp("00000000000")
                .email("admin@gmail.com")
                .password(this.passwordEncoder.encode("12345678a!"))
                .dateOfBirth(LocalDate.of(1990, 1, 1))
                .role(Set.of("ADMIN"))
                .createdAt(LocalDateTime.now())
                .contractQuantities(5L)
                .favorites(List.of())
                .properties(List.of())
                .facebook("admin")
                .instagram("admin")
                .active(true)
                .build();

        User paula = User.builder()
                .id(2L)
                .name("Paula Dos Santos")
                .phone("73999991122")
                .whatsapp("73999991234")
                .email("paula@gmail.com")
                .password(this.passwordEncoder.encode("12345678!!"))
                .dateOfBirth(LocalDate.of(1995, 1, 1))
                .role(Set.of("ADMIN"))
                .createdAt(LocalDateTime.now())
                .contractQuantities(5L)
                .favorites(List.of())
                .properties(List.of())
                .facebook("facebook.com/paula")
                .instagram("instagram.com/paula")
                .imageProfile("a1.jpg")
                .active(true)
                .build();

        User pedro = User.builder()
                .id(3L)
                .name("Pedro Rodrigues")
                .phone("73999998841")
                .whatsapp("73999993321")
                .email("pedro@gmail.com")
                .password(this.passwordEncoder.encode("12345678!!"))
                .dateOfBirth(LocalDate.of(1995, 1, 1))
                .role(Set.of("ADMIN"))
                .createdAt(LocalDateTime.now())
                .contractQuantities(5L)
                .favorites(List.of())
                .properties(List.of())
                .facebook("facebook.com/pedro")
                .instagram("instagram.com/pedro")
                .imageProfile("a2.jpg")
                .active(true)
                .build();

        if (userRepository.count() == 0) {
            log.info("=======================================================");
            log.info("Nenhum usuário encontrado, cadastrando usuários padrão.");
            log.info("=======================================================");

            userRepository.save(admin);
            userRepository.save(paula);
            userRepository.save(pedro);
        }

        if (userRepository.findById(paula.getId()).isPresent()) {
            immobileRepository.save(
                    Immobile.builder()
                            .name("Casa no campo")
                            .description("Uma bela casa de campo com um belo jardim e garagem.")
                            .address("Rua das Flores, 123")
                            .city("Florianópolis")
                            .neighborhood("Jurerê Internacional")
                            .state("Santa Catarina")
                            .garage(true)
                            .quantityBedrooms(4)
                            .quantityRooms(6)
                            .IPTU(new BigDecimal("1200.00"))
                            .price(new BigDecimal("850000.00"))
                            .suite(true)
                            .usefulArea(200.0)
                            .totalArea(300.0)
                            .quantityBathrooms(3)
                            .integrity(IntegrityEnum.NEW)
                            .sellerType(SellerTypeEnum.OWNER)
                            .age(AgeEnum.UP_TO_1_YEARS)
                            .category(CategoryEnum.SELL)
                            .createdAt(LocalDateTime.now())
                            .type(TypeEnum.HOUSE)
                            .garden(true)
                            .virtualTour(true)
                            .videos(false)
                            .beach(true)
                            .disabledAccess(true)
                            .playground(true)
                            .grill(true)
                            .energyGenerator(false)
                            .closeToTheCenter(true)
                            .elevator(false)
                            .pool(true)
                            .frontDesk(true)
                            .multiSportsCourt(false)
                            .gym(true)
                            .steamRoom(false)
                            .cableTV(true)
                            .heating(true)
                            .cabinetsInTheKitchen(true)
                            .bathroomInTheRoom(true)
                            .internet(true)
                            .partyRoom(true)
                            .airConditioning(true)
                            .americanKitchen(true)
                            .hydromassage(true)
                            .fireplace(true)
                            .privatePool(false)
                            .electronicGate(true)
                            .serviceArea(true)
                            .pub(false)
                            .closet(true)
                            .office(true)
                            .yard(true)
                            .alarmSystem(true)
                            .balcony(true)
                            .concierge24Hour(true)
                            .walledArea(true)
                            .dogAllowed(true)
                            .catAllowed(true)
                            .cameras(true)
                            .furnished(true)
                            .seaView(true)
                            .gatedCommunity(true)
                            .active(true)
                            .user(paula)
                            .favoriteUser(List.of())
                            .files(List.of("a1.jpg", "a2.jpg", "a3.webp", "a4.jpg"))
                            .build()
            );
        }

        if (userRepository.findById(paula.getId()).isPresent()) {
            immobileRepository.save(
                    Immobile.builder()
                            .name("Casa na floresta")
                            .description("Uma bela casa na floresta cercada pela natureza.")
                            .address("Rua E, 135")
                            .city("Ilhéus")
                            .neighborhood("Jurerê Internacional")
                            .state("Bahia")
                            .garage(true)
                            .quantityBedrooms(4)
                            .quantityRooms(6)
                            .IPTU(new BigDecimal("1200.00"))
                            .price(new BigDecimal("850000.00"))
                            .suite(true)
                            .usefulArea(200.0)
                            .totalArea(300.0)
                            .quantityBathrooms(3)
                            .integrity(IntegrityEnum.NEW)
                            .sellerType(SellerTypeEnum.OWNER)
                            .age(AgeEnum.UP_TO_1_YEARS)
                            .category(CategoryEnum.SELL)
                            .createdAt(LocalDateTime.now())
                            .type(TypeEnum.HOUSE)
                            .garden(true)
                            .virtualTour(true)
                            .videos(false)
                            .beach(true)
                            .disabledAccess(true)
                            .playground(true)
                            .grill(true)
                            .energyGenerator(false)
                            .closeToTheCenter(true)
                            .elevator(false)
                            .pool(true)
                            .frontDesk(true)
                            .multiSportsCourt(false)
                            .gym(true)
                            .steamRoom(false)
                            .cableTV(true)
                            .heating(true)
                            .cabinetsInTheKitchen(true)
                            .bathroomInTheRoom(true)
                            .internet(true)
                            .partyRoom(true)
                            .airConditioning(true)
                            .americanKitchen(true)
                            .hydromassage(true)
                            .fireplace(true)
                            .privatePool(false)
                            .electronicGate(true)
                            .serviceArea(true)
                            .pub(false)
                            .closet(true)
                            .office(true)
                            .yard(true)
                            .alarmSystem(true)
                            .balcony(true)
                            .concierge24Hour(true)
                            .walledArea(true)
                            .dogAllowed(true)
                            .catAllowed(true)
                            .cameras(true)
                            .furnished(true)
                            .seaView(true)
                            .gatedCommunity(true)
                            .active(true)
                            .user(paula)
                            .favoriteUser(List.of())
                            .files(List.of("b1.jpg", "b2.jpg", "b3.webp", "b4.jpg"))
                            .build()
            );
        }

        if (userRepository.findById(pedro.getId()).isPresent()) {
            immobileRepository.save(
                    Immobile.builder()
                            .name("Chalé de inverno")
                            .description("Um belo chalé de inverno, todo feito em madeira.")
                            .address("Rua das Flores, 123")
                            .city("Florianópolis")
                            .neighborhood("Jurerê Internacional")
                            .state("Santa Catarina")
                            .garage(true)
                            .quantityBedrooms(4)
                            .quantityRooms(6)
                            .IPTU(new BigDecimal("1200.00"))
                            .price(new BigDecimal("850000.00"))
                            .suite(true)
                            .usefulArea(200.0)
                            .totalArea(300.0)
                            .quantityBathrooms(3)
                            .integrity(IntegrityEnum.NEW)
                            .sellerType(SellerTypeEnum.OWNER)
                            .age(AgeEnum.UP_TO_1_YEARS)
                            .category(CategoryEnum.SELL)
                            .createdAt(LocalDateTime.now())
                            .type(TypeEnum.HOUSE)
                            .garden(true)
                            .virtualTour(true)
                            .videos(false)
                            .beach(true)
                            .disabledAccess(true)
                            .playground(true)
                            .grill(true)
                            .energyGenerator(false)
                            .closeToTheCenter(true)
                            .elevator(false)
                            .pool(true)
                            .frontDesk(true)
                            .multiSportsCourt(false)
                            .gym(true)
                            .steamRoom(false)
                            .cableTV(true)
                            .heating(true)
                            .cabinetsInTheKitchen(true)
                            .bathroomInTheRoom(true)
                            .internet(true)
                            .partyRoom(true)
                            .airConditioning(true)
                            .americanKitchen(true)
                            .hydromassage(true)
                            .fireplace(true)
                            .privatePool(false)
                            .electronicGate(true)
                            .serviceArea(true)
                            .pub(false)
                            .closet(true)
                            .office(true)
                            .yard(true)
                            .alarmSystem(true)
                            .balcony(true)
                            .concierge24Hour(true)
                            .walledArea(true)
                            .dogAllowed(true)
                            .catAllowed(true)
                            .cameras(true)
                            .furnished(true)
                            .seaView(true)
                            .gatedCommunity(true)
                            .active(true)
                            .user(pedro)
                            .favoriteUser(List.of())
                            .files(List.of("c1.webp", "c2.webp", "c3.webp", "c4.jpg"))
                            .build()
            );
        }

        if (userRepository.findById(pedro.getId()).isPresent()) {
            immobileRepository.save(
                    Immobile.builder()
                            .name("Apartamento Mobilhado")
                            .description("Apartamento mobilhado no centro de SP.")
                            .address("Guarulhos, 123")
                            .city("Florianópolis")
                            .neighborhood("Jurerê Internacional")
                            .state("São Paulo")
                            .garage(true)
                            .quantityBedrooms(4)
                            .quantityRooms(6)
                            .IPTU(new BigDecimal("1200.00"))
                            .price(new BigDecimal("850000.00"))
                            .suite(true)
                            .usefulArea(200.0)
                            .totalArea(300.0)
                            .quantityBathrooms(3)
                            .integrity(IntegrityEnum.NEW)
                            .sellerType(SellerTypeEnum.OWNER)
                            .age(AgeEnum.UP_TO_1_YEARS)
                            .category(CategoryEnum.SELL)
                            .createdAt(LocalDateTime.now())
                            .type(TypeEnum.HOUSE)
                            .garden(true)
                            .virtualTour(true)
                            .videos(false)
                            .beach(true)
                            .disabledAccess(true)
                            .playground(true)
                            .grill(true)
                            .energyGenerator(false)
                            .closeToTheCenter(true)
                            .elevator(false)
                            .pool(true)
                            .frontDesk(true)
                            .multiSportsCourt(false)
                            .gym(true)
                            .steamRoom(false)
                            .cableTV(true)
                            .heating(true)
                            .cabinetsInTheKitchen(true)
                            .bathroomInTheRoom(true)
                            .internet(true)
                            .partyRoom(true)
                            .airConditioning(true)
                            .americanKitchen(true)
                            .hydromassage(true)
                            .fireplace(true)
                            .privatePool(false)
                            .electronicGate(true)
                            .serviceArea(true)
                            .pub(false)
                            .closet(true)
                            .office(true)
                            .yard(true)
                            .alarmSystem(true)
                            .balcony(true)
                            .concierge24Hour(true)
                            .walledArea(true)
                            .dogAllowed(true)
                            .catAllowed(true)
                            .cameras(true)
                            .furnished(true)
                            .seaView(true)
                            .gatedCommunity(true)
                            .active(true)
                            .user(pedro)
                            .favoriteUser(List.of())
                            .files(List.of("d1.png", "d2.png", "d3.jpg", "d4.png"))
                            .build()
            );
        }
    }
}
