spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

info: ===== production =====

#path for save files
file.upload-image-profile-dir: "/app/images-profile"
file.upload-image-immobile-dir: "/app/files-immobile"

#path for mount files
base-url: "http://localhost:8080"
base-url-user-files-api: "/api/files/download/profile/"
base-url-immobile-files-api: "/api/files/download/immobile/"