spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/minhacasa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

images-user-path: "C:/minhacasa/images-profile"
images-immobile-path: "C:/minhacasa/images-immobile"