spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/minhacasa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

file.upload-image-profile-dir: "C:/minhacasa/images-profile"
file.upload-image-immobile-dir: "C:/minhacasa/files-immobile"
base-url: "http://localhost:8080"