spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://postgres-db:5432/minhacasa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

info: ===== production =====

#path for save files
file.upload-image-profile-dir: "/app/images-profile"
file.upload-image-immobile-dir: "/app/files-immobile"

#path for mount files
base-url: "http://localhost:8080"
base-url-user-files-api: "/api/files/download/profile/"
base-url-immobile-files-api: "/api/files/download/immobile/"