spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/minhacasa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

images-user-path: "C:/minhacasa/images-profile"